--- 
kind: Service
apiVersion: v1
metadata:
  labels:
    app: gke-info-exporter
  name: gke-info-exporter
spec:
  selector:
    app: gke-info-exporter
  ports:
    - name: metrics
      port: 8080
      targetPort: 9905
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: gke-info-exporter
  name: gke-info-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-info-exporter
  template:
    metadata:
      labels:
        app: gke-info-exporter
    spec:
      containers:
        - name: gke-info-exporter
          image: exporter:latest
          args:
          - /exporter
          - --project-id=training-300214
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gke-sa-client-secret.json
          ports:
            - name: metrics
              containerPort: 9905
          volumeMounts:
            - name: secrets
              mountPath: /secrets
          resources:
            requests:
               memory: 100Mi
               cpu: 40m
            limits:
              memory: 256Mi
              cpu: 150m   
      restartPolicy: Always
      volumes:
        - name: secrets
          secret:
            secretName: gke-info-exporter-credentials
---  
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: gke-info-exporter
  labels:
    app: gke-info-exporter
spec:
  selector:
    matchLabels:
      app: gke-info-exporter
  endpoints:
    - port: metrics